### ISSUE TITLE
Missing signature

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/mqtt-datasource#11]
Hi I tried to install the mqtt plugin, but I get "Missing Signature" in Grafana Data source overview. Will there be a version that can run under Grafana 8.x. Or due I missing something during installation?

**Comment by JFP-SG** [comment]
Hey,
Did you try to allow this unsigned plugin via Setting/Environment Variable, refering to this:
https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

Ciao Jan-Frederik

**Comment by HenrikRolandHansen** [comment]
Cheers and many thanks for the tip, it works
