### ISSUE TITLE
Error when adding source

### ISSUE THREAD

**Issue by whbruce** [grafana/mqtt-datasource#13]
New to grafana, so this may be a rookie question. I see 4 entries for the MQTT data source in the configuration view (default, 1, 2 and 3).

I built mqtt-datasource but got the following error in grafana when I tried to add it. No obvious grafana logs to share.
Running on Ubuntu 20.04, not using a container. Grafana v7.0.

**An unexpected error happened**  
Details  
Error: Minified React error #130
```
in form
    in tm
    in Unknown
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in m
    in Unknown
    in Unknown
    in t
    in t
    in s
```

**Comment by atifali** [comment]
@whbruce do you want to maybe try with Grafana v8.0?

for a streaming backend datasource plugin like this one a pre-requisite is Grafana v8.0+. see: https://grafana.com/tutorials/build-a-streaming-data-source-plugin/

will add this to the docs 😬

**Comment by whbruce** [comment]
Thanks updating to v8.0 fixed it.
