### ISSUE TITLE
Error when trying to yarn build

### ISSUE THREAD

**Issue by knubbl1983** [grafana/mqtt-datasource#21]
I get the following error when executing yarn build.

Any idea what im doing wrong?

/bin/sh: 1: mage: not found
error Command failed with exit code 127.

mage -version shows:

Mage Build Tool v1.11.0-2-g4cf3cfc
Build Date: 2021-08-22T20:05:12+02:00
Commit: 4cf3cfc
built with: go1.11.6

**Comment by whbruce** [comment]
You need to install [mage](https://magefile.org/). See [Ubuntu build instructions](https://github.com/grafana/mqtt-datasource/issues/15#issuecomment-894477802).

**Comment by knubbl1983** [comment]
mage -version gives me information about this. see my first comment.
i think its already installed.

**Comment by knubbl1983** [comment]
![image](https://user-images.githubusercontent.com/23267772/130673441-945e80b1-e9ac-4cff-8888-d1106203259d.png)

is this a problem? and why yarn build try to execute mage in sh

**Comment by atifali** [comment]
looks like this might be a problem with where `yarn build` looks for the executables.

can you try `mage build:backend` to build the backend manually.

**Comment by knubbl1983** [comment]
pi@raspberrypi:/var/lib/grafana/mqtt-datasource $ mage build:backend
Error determining list of magefiles: failed to list non-mage gofiles: exit status 1: go: finding github.com/go-logfmt/logfmt v0.3.0

this is what happend when i do `mage build:backend`

**Comment by terorie** [comment]
I've had zero problems with mage on latest master. I think this can be closed.

**Comment by atifali** [comment]
Alright then closing now! Thanks for reporting @terorie 👍
