### ISSUE TITLE
value as string, not number

### ISSUE THREAD

**Issue by DonatoD** [grafana/mqtt-datasource#24]
Hi, I'm trying to send messages as string, since I would like to use mqtt with different panels other then time series, and I need text string
I tried with different syntax but nothing. I always get a very old data )(something like " 1750 ... ") and value 0.
Is that possible?

**Comment by atifali** [comment]
Hi @DonatoD can you please provide a sample of what the messages exactly look like.
Just to clarify currently this data source only supports the format as mentioned here: https://github.com/grafana/mqtt-datasource/blob/main/README.md#known-limitations
We are working on an enhancement to provide support for more complex messages. Follow here: https://github.com/grafana/mqtt-datasource/issues/8

**Comment by DonatoD** [comment]
Hi thanks for your reply. I mean any kind of string, text. The format it's not a problem, it,s possible to arrange it as the mqtt datasource requires. This because I would like to use it with other panel, like html, svg, and so on so that I can have more control and custom result
So whatever kind of string/words not just number. Fo example if I try sto send "start" as payload, I see 0, or nothing. I have tryed with several format, includin json
{
    "value1": "start",
    "value2": "in_progress",
    "value3": "unavailable"
}

**Comment by DonatoD** [comment]
Sorry, which the state of this integration? I tried to understand it by clicking on the various links: closed, enhancement, open ....
It's Like a stuck loop
