### ISSUE TITLE
Confusion in README.md in the "very simple JSON-formatted messages" support between single and double quotes

### ISSUE THREAD

**Issue by reind33r** [grafana/mqtt-datasource#25]
Hi !

Just to let you know that the in the JSON message sent over MQTT, the key must be enclosed in double quotes and not single quotes (as it is written in the README.md). Messages with single quotes aren't recognised by the plugin at all, and it can be painful to debug such a simple mistake... especially since it's mentionned that it's the only supported format. People might want to adhere strictly to it. (no no no, it didn't happen to me 0:) )

If you could make it clearer the README.md, it might save some time to other users!

Sincerely,

Louis

**Comment by atifali** [comment]
Thank you so much for reporting this Louis. Fixed now in: https://github.com/grafana/mqtt-datasource/blob/main/README.md#known-limitations
