### ISSUE TITLE
No data in mqtt

### ISSUE THREAD

**Issue by astrakid** [grafana/mqtt-datasource#96]
hi,
i am using grafana latest version in docker container and the latest mqtt-plugin.
my mqtt-publisher is mosquitto in another docker container. mqtt is fully functional (other containers are publishing data to mosquitto and others are subscribed t mosquitto successfully).
in grafana i am not able to get data from mqtt, although the test is succesful and i see a connections in mosquitto when connection is tested in grafana.

![image](https://github.com/grafana/mqtt-datasource/assets/5278642/308dfe87-0075-422d-8949-f52c26921b4a)

i tested several topics, from
#
mbmd/#
mbmd/sunspec1-126/#
mbmd/sunspec1-126/Frequency
mbmd/sunspec1-126/Frequency/#

nothing is giving me any data.

i verified the connection several times, it loogs good:

![image](https://github.com/grafana/mqtt-datasource/assets/5278642/db3c4563-e79c-41c6-958a-78fe22b8d15d)

any ideas?

regards,
andre

**Comment by teefixx** [comment]
Hi all, I face the same problem a FlashMQ server from VenusOS. Other clients incl python can read and write, this plugin just gets no data at all...

**Comment by astrakid** [comment]
at least i was able to receive data, but only when having timewindow set to current timeframe. my default view is covering the whole day (forecast data is included), then i don't receive anything. very annoying.

**Comment by MrG8N** [comment]
I have the similar problem. I get allways 0 data. But with MQTT Explorer and connection test all works fine .

**Comment by SummerSeaSun** [comment]
Same here no data are shown. Attached output from Inspect: Query:

```
{
  "request": {
    "url": "api/ds/query?ds_type=grafana-mqtt-datasource&requestId=Q111",
    "method": "POST",
    "data": {
      "queries": [
        {
          "datasource": {
            "type": "grafana-mqtt-datasource",
            "uid": "adkz30u2cge80d"
          },
          "hide": false,
          "refId": "B",
          "topic": "tb_temp/status/switch:0",
          "datasourceId": 1,
          "intervalMs": 30000,
          "maxDataPoints": 739
        }
      ],
      "from": "1715052995577",
      "to": "1715074595577"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "B": {
        "status": 200,
        "frames": [
          {
            "schema": {
              "refId": "B",
              "meta": {
                "typeVersion": [
                  0,
                  0
                ],
                "channel": "ds/adkz30u2cge80d/30s/tb_temp/status/switch:0"
              },
              "fields": []
            },
            "data": {
              "values": []
            }
          }
        ],
        "refId": "B"
      }
    }
  }
}
```

![image](https://github.com/grafana/mqtt-datasource/assets/6357809/b06e46e1-6655-45b7-9983-7049bc25d0bb)

**Comment by astrakid** [comment]
i think i have found the solution. when using a low interval i am getting values. to reach this approach you have to set max data points to a higher value (for my timeframe now/d+5h up to now/d-90m i need to set up 20000 max data points).

**Comment by frankvandenhurk** [comment]
It seems that it is also possible to set "Relative time" to a low value (in my case 1 minute). With the added benefit of the "live data" experience, since the Stat visualisation showes the values from the last minute in a very nice way (my source updates about every 2 seconds).

**Comment by astrakid** [comment]
that method is even smarter than my previously mentioned way. thanks for that!

**Comment by astrakid** [comment]
use relative time is a smart method
